version: 2.1
jobs:
  build:
    resource_class: xlarge
    docker:
      # image with node, npm and yarn installed
      - image: cimg/node:16.8.0
    steps:
      # checkout workspace to repo code
      - checkout

      # restore workspace if available
      # to skip re-installing node_modules
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      # install dependencies
      - run: yarn --ignore-engines --network-concurrency=1

      # save node_modules to cache
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      # build code to production file
      - run:
          name: yarn build according to branch
          command: |
            NODE_OPTIONS="--max_old_space_size=7168" yarn build --transpile-only

      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy:
    docker:
      - image: cimg/node:16.8.0
    steps:
      - attach_workspace:
          at: .

      - restore_cache:
          keys:
            - v1-npm-global

      - run:
          name: install AWS CLI
          command: |
            sudo apt-get --allow-releaseinfo-change update
            sudo apt-get install awscli

      - save_cache:
          paths:
            - ~/.npm-global
          key: v1-npm-global

      - run:
          name: deploy to aws
          command: |
            if [ -d "build/static/js" ]
            then
              gzip -9 build/static/js/*
              for i in ./build/static/js/*;
                do mv "$i" "${i%.gz}";
              done
            fi

            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              aws s3 sync build s3://zilswap-v2/production/ --delete --exclude "static/js/*"
              aws s3 sync build/static/js s3://zilswap-v2/production/static/js --delete --content-encoding gzip
              aws cloudfront create-invalidation --distribution-id="E2KAV21I2EB7LG" --paths=/*
            fi

workflows:
  build-and-deploy:
    jobs:
      - build:
          context: org-switcheo
          filters:
            branches:
              only:
                - master
      - deploy:
          context: org-switcheo
          requires:
            - build
